export enum CategoriaAtividade {
  DESENVOLVIMENTO = 'DESENVOLVIMENTO',
  CORRECAO_BUG = 'CORRECAO_BUG',
  REUNIAO = 'REUNIAO',
  TESTES = 'TESTES',
  DOCUMENTACAO = 'DOCUMENTACAO',
  DEPLOY = 'DEPLOY',
  SUPORTE = 'SUPORTE',
  ESTUDO = 'ESTUDO',
  OUTROS = 'OUTROS',
}
